/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package LibTMOA;

import LibTMOA.models.ChassisConfiguration;
import LibTMOA.models.DcMotorBase;
import org.junit.Test;

import java.util.List;

import static org.junit.Assert.*;

public class TMOATest {
    @Test public void testSomeLibraryMethod() {
        TMOA classUnderTest = new TMOA(getTestingConfiguration());

        //assertTrue("someLibraryMethod should return 'true'", classUnderTest.someLibraryMethod());
    }

    public static ChassisConfiguration getTestingConfiguration(){
        return new ChassisConfiguration(
            List.of(
                new TestDcMotor( (byte) 0),
                new TestDcMotor( (byte) 1),
                new TestDcMotor( (byte) 2),
                new TestDcMotor( (byte) 3)
            )
        );
    }
}

class TestDcMotor extends DcMotorBase{

    public TestDcMotor(byte id) {
        super(id);
    }

    @Override
    public double getPower() {
        return super.getPower();
    }

    @Override
    public void setPower(double power) {
        System.out.println("[Motor " + super.getId() + "] - Now, power is: " + super.getPower());
        super.setPower(power);
    }
}
